Panels:
  - Class: rviz_common/Displays
    Name: Displays

Visualization Manager:
  Displays:
    - Class: rviz_default_plugins/RobotModel
      Name: RobotModel
      Enabled: true
      Description Source: Topic
      Description Topic: /robot_description
      Alpha: 1.0
      Visual Enabled: true
    
    - Class: rviz_default_plugins/TF
      Name: TF
      Enabled: true
      Show Arrows: true
      Show Axes: true
      Show Names: false
      Frame Timeout: 15
      Marker Scale: 1
    
    - Class: rviz_default_plugins/Grid
      Name: Grid
      Enabled: true
      Plane Cell Count: 10
      Reference Frame: world
      Color: 160; 160; 164
  
    - Class: rviz_default_plugins/Image
      Name: Overhead Camera
      Enabled: true
      Topic: /overhead_camera/image_raw
      Transport Hint: raw
      Queue Size: 10
      Min Value: 0
      Max Value: 255
      Normalize Range: false
      Unreliable: false
      Image Rendering: 0

  Global Options:
    Fixed Frame: world
    Background Color: 48; 48; 48
    Frame Rate: 30
  
  Tools:
    - Class: rviz_default_plugins/Interact
    - Class: rviz_default_plugins/MoveCamera
    - Class: rviz_default_plugins/Measure
    - Class: rviz_default_plugins/PublishPoint
  
  Views:
    Current:
      Class: rviz_default_plugins/Orbit
      Distance: 2
      Pitch: 0.5
      Yaw: 0.8
      Focal Point:
        X: 0
        Y: 0
        Z: 0
      Target Frame: <Fixed Frame>
